# the master key under which the metadata dictionary should be stored
metadata_master_key:
- cg

# Debug - turn on to get lots of information about the nodes
debug:
- on

# Nodes from which to get the metadata. The format is:
# key, node_title, output_or_input
# where key is the key under which this data is to be stored
# node_title is the title of the node in your workflow (use #n to get the n'th instance)
# output_or_input is the name of an output, or of an input (or widget) of a node (append '!' to skip outputs when there are both inputs and outputs)
#
#Turn debug on to list node names and the available outputs and inputs
metadata_sources:
- ckpt_name, CheckpointLoaderSimple, ckpt_name
- prompt, TwoClipTextEncode, prompt
- negative_prompt, TwoClipTextEncode, negative_prompt
- steps, KSampler, steps
- seed, KSampler, seed
- cfg, KSampler, cfg
- sampler, KSampler, sampler_name
- scheduler, KSampler, scheduler

# output nodes on the Get Metadata node, and their type (default is STRING)
get_metadata_outputs:
- ckpt_name
- prompt
- negative_prompt
- seed, INT
- steps, INT
- cfg, FLOAT
- sampler
- scheduler
- comment