# the master key under which the metadata dictionary should be stored
metadata_master_key:
- cg

# Debug - turn on to get lots of information about the nodes (values 0,1,2)
debug:
- 2

# Nodes from which to get the metadata. The format is:
# node_title[#n].input[, key]
# node_title is the title of the node in your workflow (use #n to get the n'th instance)
# input is the name of an input (or widget) of a node
# key is the key under which this data is to be stored (if not specified, the name of the input is used)
#Turn debug on to list node names and the available outputs and inputs
metadata_sources:
- CheckpointLoaderSimple.ckpt_name
- TwoClipTextEncode.prompt
- TwoClipTextEncode.negative_prompt
- KSampler.steps
- KSampler.seed
- KSampler.cfg
- KSampler.sampler_name, sampler
- KSampler.scheduler

# keys to be output by the Get Metadata node, and their type (default is STRING)
get_metadata_outputs:
- ckpt_name
- prompt
- negative_prompt
- seed, INT
- steps, INT
- cfg, FLOAT
- sampler
- scheduler
- comment